version: '3'
services:
  rails-app:
    image: task_1:v1
    container_name: rails-app
    volumes:
      - .:/rails-app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
  nginx:
      build: .
      container_name: nginx
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 80:80
      depends_on:
          - rails-app
volumes:
  rails-app-data:
  bundle: